### ISSUE TITLE
Update to Java 11

### ISSUE THREAD

**Issue by hugith** [undur/vermilingua-maven-plugin#12]
If there are no objections I think it's prudent to be on the latest LTS. I also really want some of those more recent APIs.

This only applies to development of the plugin itself, not the applications/frameworks the plugin is used to build (although the build server/Maven itself will of course have to run on Java 11).

Tested upgrade in 0e932817cd8ff5f4b97b5031626a4dbe014d5cb1

**Comment by paulhoadley** [comment]
I support this idea. The more reasons I have to upgrade my entire ecosystem past Java 8 the better.
