### ISSUE TITLE
Support building old-style WO .framework bundles (for use with ant)

### ISSUE THREAD

**Issue by hugith** [undur/vermilingua-maven-plugin#14]
We've already implemented maven style jar-bundled frameworks (see #4).

But wolifecycle doesn't just create a jar framework for ues with maven, it also builds the old style `SomeFramework.framework` folder for use with ant projects. These folders are essentially identical to the structure of the jar, except they also contain the `Resources/Java` directory that contains the framework's java sources, plus any added libraries.

Although I'm not extremely excited about the older style, It's probably prudent to do both, so a mavenized project (e.g. Wonder) can generate frameworks for use by Ants.

**Comment by paulhoadley** [comment]
Hot take: let's not do this. You're living in the past, man. We should be encouraging a Maven-only toolchain, not providing a crutch for Ant. Adding this will then create an obligation to maintain it.

What do you think of that view?

**Comment by hugith** [comment]
I like the way you think. And you're absolutely right as well. I have no idea why I'm writing out an old style build no one asked for. Closed.
