### ISSUE TITLE
Figure out where ${build.finalName} ends and bundle name begins

### ISSUE THREAD

**Issue by hugith** [undur/vermilingua-maven-plugin#15]
With reference to #8.

Currently we're using ${build.finalName} as the name of the built Application. Everywhere. I've got a feeling this is wrong, since people might want to add stuff like classifiers, timestamps etc. to the build product, stuff we don't neccessarily want reflected in the bundle name.

Correct semantics are probably:
1) ${finalName} should only control the name of the WOA
2) The actual application name comes from build.properties/${project.name}

**Comment by timcu** [comment]
When I was using `ant` I would specify 

    <property name="build.app.name" value="${project.name}${DSTAMP}${TSTAMP}" />

and it would change the folder name and the script name. ie `MyApp20210716125959.woa/MyApp20210716125959`. 

Now I use `wolifecycle-maven-plugin` and specify 

    <properties><build_timestamp>${maven.build.timestamp}</build_timestamp>...</properties>
    <build><finalName>${project.artifactId}${maven.build.timestamp}</finalName>...</build>

and only the folder name gets changed. ie `MyApp20210716125959.woa/MyApp`. I can work with either way but finding the `wolifecycle-maven-plugin` way slightly easier when I deploy new versions. And, as you surmised, it is very important to me to be able to add a timestamp to the folder name. 

I am not sure what you are calling the Application name. I searched through my built app and found another file `MyApp20210716125959.woa/Contents/MacOS/MyApp20210716125959`. I don't think this is being called so I don't care if this has the timestamp or not.

**Comment by hugith** [comment]
Thanks for the input @timcu! I agree that it's best to change nothing inside the bundle, i.e. use the finalName only for the .WOA.

And pardon for the ambigious terms. When I said "application name" I have probably said "bundle name" or "project name". As in "The name given to the project in WOLips and that WO will subsequently use to identify the bundle".

**Comment by hugith** [comment]
`finalName` now sets the name of the .WOA folder and the application .jar. Launch scripts (and the references to them in `Info.plist`) remain the same as the bundle name.
