### ISSUE TITLE
Allow building of project without components/resources

### ISSUE THREAD

**Issue by hugithordarson** [undur/vermilingua-maven-plugin#16]

**Comment by paulhoadley** [comment]
This one sounds interesting. What's the use case here?

**Comment by hugith** [comment]
Well, none of these folders are technically required. A regular maven project with a single DirectAction class  and a `build.properties` to identify the primary class, could be a valid WO project.

A side effect is that it allows you to create a WOA out of any java project (as long as you add that `build.properties`). I was trying it out to test deployment of [this](https://github.com/ngobjects/ng-objects) yesterday. It feels… interesting.

**Comment by hugithordarson** [comment]
Components/Resources/WebServerResources are now optional, so we can build and launch any general purpose java project.
