### ISSUE TITLE
flattenComponents

### ISSUE THREAD

**Issue by hugithordarson** [undur/vermilingua-maven-plugin#2]
Note: Error on duplicate component name

**Comment by paulhoadley** [comment]
We discussed this on Slack. @hugith:

> Regarding `flattenComponents` — shouldn't that just be default behviour? I mean, does a deployed WebObjects application have any idea how to locate a component in a subfolder

We think the answer is no, WebObjects can't retrieve a _component_ from a sub-folder. In which case, me:

> Assuming that's true, there's almost no point in `flattenComponents` being an _option,_ is there? That is, under what circumstances would it make sense to set it `false`?

I think we're in furious agreement on this.

**Comment by hugithordarson** [comment]
Issue only says I have to do it, not that I have to do it well, so closed.
