### ISSUE TITLE
Look into replacing the manual classpath generation with a simple wildcard

### ISSUE THREAD

**Issue by hugithordarson** [undur/vermilingua-maven-plugin#26]
We're currently generating a classpath file that contains a list of all the jars inside ```Contents/Java```. We should be able to replace this with a wildcard.

**Comment by hugithordarson** [comment]
Not planning on doing this anytime soon

**Comment by paulhoadley** [comment]
> Not planning on doing this anytime soon

Why not? Is it hard?

**Comment by hugithordarson** [comment]
In theory, no, not hard. It should be enough to just copy the jars into a flat structure (wildcards on the classpath don't enter subfolders) and set the classpath to `APPROOT/Resources/Java/*`.

But what got me thinking is that we lose control over classpath ordering, which is something I think Wonder cares about, what with all the patches and WO overrides. A classpath wildcard just gives us alphabetical ordering which might not be what we want.

**Comment by paulhoadley** [comment]
> which is something I think Wonder cares about

Yeah. To be fair, it's something _I_ occasionally care about, too, for stuff like overriding the version of a transitive dependency that I can't change directly, say. I hadn't considered ordering—I think that pretty much kills this idea, doesn't it?

Also: on ordering, how is `vermilingua` doing that? Because the generated `UNIXClassPath.txt` seems wildly different to a `wolifecycle` classpath. I forgot to open a ticket for that observation earlier, because I glossed over it, not considering that it defined the runtime ordering. Should we look at that?

**Comment by paulhoadley** [comment]
Actually, eyeballing it, the `UNIXClassPath.txt` in a `wolifecycle` build looks _sorted alphabetically._ Is this something that `vermilingua` actually _fixes?_

**Comment by hugithordarson** [comment]
Oh… Good catch! Yeah, vermilingua apparently preserves the classpath generated by maven (i.e. if you change the dependency order i maven, it gets reflected in the classpath). I don't remember how deeply I dug into this when writing the plugin, I'm blindly calling the Maven APIs `MavenProject.getArtifacts()` and trusted it to do the right thing :).

From a quick look, it seems the classpath generated by vermilingua is in line with the classpath generated by Eclipse when launching in development, which I think should be desirable?

**Comment by hugithordarson** [comment]
…this all at least probably means that classpath ordering doesn't really matter WRT Wonder. After all, it spends half it's code doing classpath reordering on application launch :)

**Comment by paulhoadley** [comment]
But it also means I must be lying to myself when I say:

> it's something I occasionally care about, too, for stuff like overriding the version of a transitive dependency that I can't change directly

I suspect what I've been relying on is merely dependency _overriding_ rather that dependency _ordering._ Phew, for a minute there, I thought I was going mad.

In any case, I imagine what `vermilingua` is doing is better than `wolifecycle`, so let's just back away slowly from this ticket now.
