### ISSUE TITLE
Resource "filtering" by maven-resources-plugin gets stomped

### ISSUE THREAD

**Issue by paulhoadley** [undur/vermilingua-maven-plugin#27]
### Background

I make some limited use of the ["filtering"](https://maven.apache.org/plugins/maven-resources-plugin/examples/filter.html) offered by `maven-resources-plugin`. Specifically, I have some properties in `Properties` like this:

```
net.logicsquad.AppInfo.groupId=${project.groupId}
net.logicsquad.AppInfo.artifactId=${project.artifactId}
net.logicsquad.AppInfo.version=${project.version}
net.logicsquad.AppInfo.name=${project.name}
```

These are then baked into the app bundle at build time, and allow me to, say, display the app version in-app at runtime using the `version` property.

### Problem

Using `vermilingua-maven-plugin`, I can see that filtering occurs:

```
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ Juno ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 273 resources
```

But the file at `Contents/Resources/Properties` is _not_ the post-filtering version of `Properties`. There _is_ a post-filtering version left in `classes/Properties`, though.

### Solution

At the moment I would only be guessing, but I _imagine_ that `vermilingua-maven-plugin` is copying resources directly from `src/main/resources` (I've set `<woresourcesFolderName>resources</woresourcesFolderName>`) into the bundle, rather than using the post-filtering staging area—which is `classes`? Alternatively, I could see an argument that I am mixing concepts here—perhaps that _is_ all `vermilingua-maven-plugin` should be doing, and I've been taking advantage of the "resources confusion" in `wolifecycle-maven-plugin` and shouldn't expect this to work? I might make some further observations after splitting out a `woresources` directory, but @hugithordarson, jump in and let me know what you think.

**Comment by paulhoadley** [comment]
Yeah, that's pretty much the answer: if I move `resources` → `woresources`, create a new `resources` and stick a properties file in it expecting property replacement via filtering:

* it _does_ get filtered; but
* the resulting file ends up in `classes` and the JAR, but _not_ in the WOA bundle (outside the JAR, anyway)—so it's not going to be available (automatically, at least) to `ERXProperties`, is it?

The correct answer here could _easily_ be that I just need to change the way I'm doing this.

**Comment by hugithordarson** [comment]
Yeah, I think you've been benefitting from wolifecycle's sometimes confusing resource stuff. The maven resources plugin is really geared towards java classpath resources, while `vermilingua` will just blindly dump everything from `src/main/woresources` into your bundle's Resources directory.

I think the easiest way to handle this would be to keep these properties in a separate java classpath resource properties file and then just read them from the classpath (that's what I do with a similar case). If you need the values in NSProperties/ERXProperties, you can add them using something like 

```
try( InputStream is = getClass().getResourceAsStream( "/my-maven.properties" )) {
	NSProperties._getProperties().load( is );
}
catch( IOException e ) {
	throw new UncheckedIOException( e );
}
```

**Comment by paulhoadley** [comment]
> Yeah, I think you've been benefitting from wolifecycle's sometimes confusing resource stuff.

I agree. I'm happy to close this and use the kind of approach you suggest.
