### ISSUE TITLE
flattenResources

### ISSUE THREAD

**Issue by hugithordarson** [undur/vermilingua-maven-plugin#3]

**Comment by paulhoadley** [comment]
Is this even useful? I've certainly hard-wired it to `false` in my parent POM, and never use it. WebObjects can find "resources" in sub-folders at runtime, so what's the point?

**Comment by hugithordarson** [comment]
Yeah, same here — it's pretty much just here to as a "just in case someone needs it". Think I'll just close the issue and reopen if someone requests it.

**Comment by paulhoadley** [comment]
Oh yeah, I meant "let's discuss _never_ implementing it". It's in the README as "Work in progress":

> `flattenResources` has not yet been implemented.

Can I kill that in the README, then we close this ticket, and just never mention it again?

**Comment by hugithordarson** [comment]
Absolutely!

**Comment by hugithordarson** [comment]
Although it might merit a mention in the "differences from wolifecycle" part

**Comment by paulhoadley** [comment]
Opened #32.
