### ISSUE TITLE
Is JAR name using project.name instead of project.name.lowercase?

### ISSUE THREAD

**Issue by paulhoadley** [undur/vermilingua-maven-plugin#30]
My observation is that for a project named "Juno", `wolifecycle` produces `juno.jar`, but `vermilingua` produces `Juno.jar`. I don't know whether the explanation in the title is correct, but certainly both those properties are present in `build.properties`. In any case, it's not like it matters, just pointing out a difference between `vermilingua` and our "reference implementation".

**Comment by hugithordarson** [comment]
I don't think it matters much but it's easy to change (although I think I'll use toLowerCase() on the project's name instead of using `project.name.lowercase` (since the project will read it's name from the Maven project's name if there's no `build.properties`.
