### ISSUE TITLE
Write unit tests/integration tests of the build process

### ISSUE THREAD

**Issue by hugith** [undur/vermilingua-maven-plugin#5]
Find out how, then do.

**Comment by paulhoadley** [comment]
As mentioned on Slack, I've done this in another plug-in project using `com.soebes.itf.jupiter.extension.itf-maven-plugin`. Where by "done this" I mean "done the absolute bare minimum to prove the concept". I'd be happy to take a look at getting something working for this project.

**Comment by hugith** [comment]
I'd love that!

On a related note I started work yesterday on splitting the "build" part of the plugin away from the "maven plugin" part (which is why it looks a little wonky at the moment), partly to make the build process testable without maven and partly because it can probably be considered good design.

**Comment by paulhoadley** [comment]
I've added a super-trivial integration test in PR #18. See what you think.
