### ISSUE TITLE
Set up Github Actions to run a build/test

### ISSUE THREAD

**Issue by hugith** [undur/vermilingua-maven-plugin#9]
Use github actions to build/test

**Comment by paulhoadley** [comment]
Take a look at my #17: I've just added a minimal "build" action to run `mvn verify` on push.

**Comment by paulhoadley** [comment]
Heh, I'll check out the build failure there.

**Comment by paulhoadley** [comment]
Ah yeah, right—the project is going to need to know about the WOCommunity repo so that we can build a WebObjects/Wonder project in testing. I don't see any way around that. I'll open another PR shortly.

**Comment by hugith** [comment]
Thanks! My immediate thoughts are that I don't think we need to include the WO libraries. A WOA can be built fine without them, it just won't run (which it doesn't need to anyway). I'd like us to consider releasing the plugin on Maven Central, so a dependency on `maven.wocommmunity.org` could be problematic, even if it's just in the tests.

**Comment by paulhoadley** [comment]
Hmm, I hadn't thought of any of that. What I can do instead of adding the repo is pull those dependencies. But then we're not testing whether the plugin puts those dependencies in the build product correctly—isn't that something we care about? (I mean, we're not testing _anything_ at the moment, beyond that the build succeeds. But in theory we _would_ test that at some point.)

Anyway, for now I will pull the WebObjects/Wonder dependencies.

**Comment by paulhoadley** [comment]
Err, hold on... what are either of us talking about? The bundle won't _build_ because it won't _compile._ Have I mis-understood what you were suggesting?

**Comment by hugith** [comment]
Good point. But the only thing the plugin does is copy dependencies to a directory structure in the WOA based on groupId/artifactId/version. If it does that correctly for _any_ dependency, I think we can safely assume it's going to work for WO/Wonder dependencies as well.

**Comment by paulhoadley** [comment]
Yeah, true enough. So you want me to mock up this test project so the Java is WebObjects-free? (What's the issue with having `maven.wocommunity.org` in the POM anyway?)

**Comment by hugith** [comment]
> Err, hold on... what are either of us talking about? The bundle won't _build_ because it won't _compile._ Have I mis-understood what you were suggesting?

Don't reference any WO/Wonder classes in the test project, just include any old random class so the compiler has something to work with.

I think of the plugin as something that builds a runnable out of any java project including it's dependencies. Some of those projects just happen to be WebObjects projects and we add some WO specific files to make WO happy :)

**Comment by hugith** [comment]
> Yeah, true enough. So you want me to mock up this test project so the Java is WebObjects-free? (What's the issue with having `maven.wocommunity.org` in the POM anyway?)

There's probably not a technical issue since the repository reference wouldn't be in the project's main pom file (which would prevent it from being submitted to Maven Central).

However, it fixes the plugin to wocommunity.org and breaks the build if maven.wocommunity.org goes down/changes domain names/loses old dependencies/other problems with 3rd party repos. I do think we should keep proprietary repos and libraries (including WO) away from the plugin and the build process.

**Comment by paulhoadley** [comment]
Yep, all fair enough. Fixed in #20.

**Comment by hugith** [comment]
Holy crap, it's working. This is awesome!
